---
# This role is experimental and still a work in progress...
# TODO: Initial attempt will fail, currently requires a "cloudflared tunnel login" which prompts the user to visit the site
# Currently this role assumes you've already performed the cloudflared login steps.
- name: install golang packages
  apt:
    name:
      - 'golang-go'
      - 'make'
    state: present
    update_cache: yes
  register: apt_install_cloudflared_deps
  retries: 5
  until: apt_install_cloudflared_deps is success

- name: clone cloudflared repository locally
  git:
    repo: https://github.com/cloudflare/cloudflared.git
    dest: cloudflared
    version: '{{ cloudflared_version }}'

- name: compile cloudflared binary
  make:
    chdir: cloudflared
    target: cloudflared
  register: cloudflared_binary

- name: copy cloudflared binary to /usr/local/bin
  command:
    cmd: cp cloudflared /usr/local/bin
    chdir: cloudflared
  when: cloudflared_binary.changed

- name: create cloudflared config directory
  file:
    path: /etc/cloudflared
    state: directory
    owner: root
    group: root
    mode: '0755'

- name:  copy cloudflared config.conf
  template:
    src: config.yml.j2
    dest: /etc/cloudflared/config.yml
  notify:
    - restart cloudflared

- name: copy cloudflared cert
  copy:
    src: '{{ item }}'
    dest: '/etc/cloudflared/cert.pem'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - cert.pem
  notify:
    - restart cloudflared

- name: initialize cloudflared tunnel to api-server
  command: cloudflared service install
  when: cloudflared_binary.changed
  notify:
    - restart cloudflared
