---
- name: pacman upgrade
  pacman:
    upgrade: yes
    update_cache: yes
  register: pacman_upgrade
  retries: 5
  until: pacman_upgrade is success

- name: install packages
  pacman:
    name: '{{ common_packages }}'
    update_cache: yes
  register: pacman_install_common
  retries: 5
  until: pacman_install_common is success

- name: enable required cgroup features
  lineinfile:
    path: '{{ common_rpi_cmd_file }}'
    state: present
    backrefs: true
    regexp: '^(.*elevator=noop(?<!cgroup_enable=memory cgroup_memory=1))$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
  notify: reboot hosts

- name: check for yay
  stat:
    path: /usr/bin/yay
  register: yay

- name: create temp folder
  tempfile:
    state: directory
    suffix: yay
  register: tempfolder
  become: no
  when:
    - not yay.stat.exists

- name: checkout yay repo
  git:
    repo: https://aur.archlinux.org/yay.git
    version: master
    dest: "{{ tempfolder.path }}"
    depth: 1
  become: no
  when:
    - not yay.stat.exists

- name: build and install yay
  command:
    chdir: "{{ tempfolder.path }}"
    cmd: makepkg -si --noconfirm
  become: no
  when:
    - not yay.stat.exists

- name: remove temp folder
  file:
    path: "{{ tempfolder.path }}"
    state: absent
  when:
    - not yay.stat.exists
