---
- name: preflight checks
  include_tasks: pre_checks.yml

- name: include initialize tasks
  include_tasks: initialize.yml
  when: inventory_hostname == cluster_main_master

- name: include join tasks
  include_tasks: join.yml
  when: inventory_hostname != cluster_main_master
