---
- hosts: masters
  become: true
  roles:
    - keepalived
    - haproxy
    - cluster
#    - {
#        role: initial-master,
#        when: "groups['masters'][0] == inventory_hostname",
#      }
#    - { role: cni, when: "groups['masters'][0] == inventory_hostname" }
#    - {
#        role: other-masters,
#        when: "groups['masters'][0] != inventory_hostname",
#      }
