---
- hosts: all
  become: true
  gather_facts: false
  vars_prompt:
    name: "nuke_confirmation"
    prompt: "Are you sure you want to run this playbook? This will DESTROY your cluster. Answer with 'YES'"
    default: "NO"
    private: no
  any_errors_fatal: yes
  tasks:
    - name: check confirmation
      fail: msg="playbook run confirmation failed"
      when: nuke_confirmation != "YES"

    - name: reset kubeadm
      command:
        cmd: kubeadm reset --force
        removes: /etc/kubernetes/admin.conf
      register: kubeadm_reset
      retries: 5
      until: kubeadm_reset is success

    - name: reset iptables
      command:
        cmd: "{{ item }}"
      loop:
        - iptables -P INPUT ACCEPT
        - iptables -P FORWARD ACCEPT
        - iptables -P OUTPUT ACCEPT
        - iptables -t nat -F
        - iptables -t mangle -F
        - iptables -F
        - iptables -X
      when: kubeadm_reset.changed
